# Generated by Django 2.2.24 on 2021-12-13 12:07

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0011_auto_20211212_1559"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 12, 15, 12, 7, 27, 874776, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        ),
    ]
